Fix sensor naming to avoid crashing homebridge on duplicates.
amlinger/homebridge-telldus-tdtool pull request #25
Opened 2016-10-09 14:34 UTC by jannylund

Starting homebridge with 9 sensors made it crash with no error on registering the second sensor.

```
[10/9/2016, 5:30:17 PM] [Telldus-TD-Tool] Initializing Telldus-TD-Tool platform...
[10/9/2016, 5:30:17 PM] [Telldus-TD-Tool] Loading devices...
[10/9/2016, 5:30:17 PM] [Telldus-TD-Tool] Found no items of type "device".
[10/9/2016, 5:30:17 PM] [Telldus-TD-Tool] Found 9 items of type "sensor".
[10/9/2016, 5:30:17 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer'...
[10/9/2016, 5:30:17 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer'...
```

This PR add's the sensor's ID to the name and makes it visible in Homekit.

```
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing Telldus-TD-Tool platform...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Loading devices...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Found no items of type "device".
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Found 9 items of type "sensor".
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 31'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 11'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 142'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 113'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 114'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 41'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 121'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 61'...
[10/9/2016, 5:33:15 PM] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 74'...
```

I'm not sure how this works in homekit after renaming and restarting, so it might require some testing still.

2016-10-09 15:39 UTC, jannylund commented
Would it make more sense to rename 'Thermometer' to ' Sensor' in this case to avoid confusion? Or set the name after a model was created so it could simply reproduce the classname?

2016-10-09 17:56 UTC, amlinger commented
Hi @jannylund,

Thanks for taking the time to write a couple of PR:s.

I agree that Thermometer is a poor name for this in the current implementation, although name should probably not even be decided here, but rather at instance level.

However, I like this solution so let's go with it in the meantime.

2016-10-09 18:00 UTC, amlinger requested changes
I like your implementation, just a few nitpicks that I would like addressed before merging to keep the project consistent.

Thanks for contributing!

2016-10-09 18:00 UTC, amlinger commented on src/index.js
> +        sensors.forEach((current, index) => {sensors[index].name = 'Thermometer ' + current.id})
Try to avoid using string concatenation and use a template string instead.

2016-10-09 18:00 UTC, amlinger commented on src/index.js
> -
Please leave this line be, as removing it really hasn't that much to do with the intention of the PR.

2016-10-09 19:37 UTC, jannylund commented on src/index.js
> -
Fixed. This was by accident.

2016-10-09 19:37 UTC, jannylund commented on src/index.js
> +        sensors.forEach((current, index) => {sensors[index].name = 'Thermometer ' + current.id})
Fixed.

2016-10-10 19:13 UTC, amlinger approved these changes

2016-10-10 19:13 UTC, merged