Add support for negative temperatures
amlinger/homebridge-telldus-tdtool pull request #26
Opened 2016-10-09 15:04 UTC by jannylund

The default characteristics does not support negative temperatures. This is not logged as an error anywhere, but the data is not passed on to homekit.

Fix is done according to comment here: https://github.com/nfarina/homebridge/issues/480#issuecomment-173663221

*NOTE:* This PR contains also my other PR, so please review/merge that first.

2016-10-09 18:05 UTC, amlinger requested changes
Thanks for taking the time to fix this!

Please consider adding a comment about why that property is set to 50, and rebase your branch on master to let us avoid conflicts when merging, and letting branches be independent of each other.

2016-10-09 18:05 UTC, amlinger commented on src/lib/telldus-accessory.js
> +      { minValue: -50 }
Cool, I did not know about this:)

Please consider adding a comment about why this is here, like -50 degrees being the coldest one could expect from a thermometer.

2016-10-09 19:52 UTC, jannylund commented on src/lib/telldus-accessory.js
> +      { minValue: -50 }
Commented.

2016-10-09 19:53 UTC, jannylund commented
Rebased onto master, so a single commit now. :)

2016-10-10 19:11 UTC, amlinger approved these changes

2016-10-10 19:12 UTC, merged

2016-10-10 19:12 UTC, amlinger commented
Great work, thanks!