Use config.json for configuring sensors.
amlinger/homebridge-telldus-tdtool pull request #31
Opened 2016-10-20 23:10 UTC by jannylund

This PR adds the functionality to use config file as documented in https://github.com/amlinger/homebridge-telldus-tdtool/issues/30

```
"platforms": [
        {
            "name": "TellstickDuo",
            "platform": "Telldus-TD-Tool",
            "sensors": [
                {
                    "id": 114,
                    "model": "temperaturehumidity",
                    "name": "Bathroom"
                },
                {
                    "id": 142,
                    "model": "temperature",
                    "name": "Sauna"
                },
                {
                    "id": 74,
                    "model": "temperature",
                    "name": "Freezer"
                }
            ]
        }
    ]
```

- Leaving out the `sensors` array or adding an empty array, it will work as before (Except the removed feature override sensortype, since that is done in config file)
- Adding a `sensors` array brings the following features:
 - No false sensors will show up.
 - Setting the name in `config.json` ensures it's always the same (correct) name.
 - Setting the proper model in `config.json` allows reconfiguration of false `temperaturehumidity` as `temperature`.

Each sensor need to have two mandatory members, `id` (to identify it uniquely) and `model` (since we don't know that at this stage).

2016-10-22 15:53 UTC, jannylund commented
Updated PR to fix the case where the `sensor()` method return `undefined` which renders homebridge dead. This was actually a bug that could happen previously as well, if telldusd was restarted after homebridge.

2016-10-24 19:56 UTC, pkempe commented
Using the below config.json, I can't get the filter to work. Sensors which are not listed in the config still show up, e.g. "Thermometer 1", even though the tdtool output for that particular sensor is

````type=sensor	protocol=mandolyn	model=temperaturehumidity	id=1	temperature=-50.0	humidity=0	time=2016-10-22 08:01:13	age=222858````.

````
    "platforms": [
	{
   	 "platform" : "Telldus-TD-Tool",
   	 "name" : "Telldus-TD-Tool",
         "sensors": [
                {
                    "id": 14,
                    "model": "temperaturehumidity"
                },
                {
                    "id": 21,
                    "model": "temperaturehumidity"
                },
                {
                    "id": 22,
                    "model": "temperaturehumidity"
                },
                {
                    "id": 13,
                    "model": "temperaturehumidity"
                },
                {
                    "id": 238,
                    "model": "temperaturehumidity"
                },
                {
                    "id": 11,
                    "model": "temperaturehumidity"
                },
                {
                    "id": 12,
                    "model": "temperaturehumidity"
                },
                {
                    "id": 23,
                    "model": "temperaturehumidity"
                }
            ]
     }
     ]
````

PS. Do I really need to clear out the accessories and persist folders, change the MAC and pin of Homebridge in config.json in order to test this? Is there a better way?

2016-10-24 21:35 UTC, jannylund commented
@pkempe strange, that should not be the case. With this PR, unnamed sensors should be named "Sensor 14", etc, and nothing related to "Termomether xx" should be visible.

I'm not 100% sure on the need to clear things out of homekit though.

Can you please paste the log you see when starting up homekit with this PR merged?

If this doesn't work, please try installing from https://github.com/jannylund/homebridge-telldus-tdtool/tree/develop (Which is similar, but with all PR's merged)

2016-10-24 21:55 UTC, jannylund commented
@pkempe I confirmed there is no need to clear out anything. Just removing one of these instances from your config and restarting homebridge is enough. 

You should see something like this in startup:

```
[10/25/2016, 12:52:06 AM] [TellstickDuo] Found 6 items of type "sensor" from "config.json".
[10/25/2016, 12:52:06 AM] [TellstickDuo] Initializing platform accessory 'Bastu'...
[10/25/2016, 12:52:06 AM] [TellstickDuo] Initializing platform accessory 'Garderob'...
[10/25/2016, 12:52:06 AM] [TellstickDuo] Initializing platform accessory 'Badrum'...
[10/25/2016, 12:52:06 AM] [TellstickDuo] Initializing platform accessory 'Utomhus'...
[10/25/2016, 12:52:06 AM] [TellstickDuo] Initializing platform accessory 'Garage'...
[10/25/2016, 12:52:06 AM] [TellstickDuo] Initializing platform accessory 'Frysen'...
```

2016-10-25 04:39 UTC, pkempe commented
Here's there log:

````
Oct 25 06:35:06 rpi homebridge[10776]: [2016-10-25 06:35:06] [Telldus-TD-Tool] Found 12 items of type "sensor".
Oct 25 06:35:06 rpi homebridge[10776]: [2016-10-25 06:35:06] [Telldus-TD-Tool] Model "1A2D" is not supported, try [selflearning-switch, codeswitch, selflearning-dimmer, humidity, temperature, temperaturehumidity]. If you stillhave not found what you're looking for, submit a pull at https://github.com/amlinger/homebridge-telldus-tdtool
Oct 25 06:35:06 rpi homebridge[10776]: [2016-10-25 06:35:06] [Telldus-TD-Tool] Initializing platform accessory 'Utomhusbrytare'...
Oct 25 06:35:06 rpi homebridge[10776]: [2016-10-25 06:35:06] [Telldus-TD-Tool] [Utomhusbrytare]: getServices called
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Brytare 1'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] [Brytare 1]: getServices called
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Brytare 2'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] [Brytare 2]: getServices called
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 177'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 11'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 14'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 12'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 13'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 21'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 22'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 23'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 1'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 43'...
Oct 25 06:35:07 rpi homebridge[10776]: [2016-10-25 06:35:07] [Telldus-TD-Tool] Initializing platform accessory 'Thermometer 141'...
Oct 25 06:35:07 rpi homebridge[10776]: Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
````

2016-10-25 04:44 UTC, pkempe commented
Considering the above, it seems I have not correctly installed the PR properly. Isn't `git pull origin pull/31/head)`; `npm run build` and then copying the dist folder contents all that's required?

2016-10-25 19:07 UTC, jannylund commented
@pkempe yes, I confirmed that it works if I do it that way. (however I run `npm install` instead, which then calls `npm run build`.  

If you still have issues, maybe try to make a clean clone of this repo. (or simply clone my fork and use the develop branch).

2016-10-29 19:21 UTC, amlinger requested changes
I very much like the implementation, although I have a few nit picks.

2016-10-29 19:21 UTC, amlinger commented on src/index.js
> +    this.senzors = config["sensors"] || [];
Why not `sensors`? I'm also not sure why this would need to be a instance variable, when `this.devices` is not.

2016-10-29 19:21 UTC, amlinger commented on src/index.js
> +      if (this.senzors.length > 0) {
I'd rather rely on `this.config.sensors`.

2016-10-29 19:21 UTC, amlinger commented on src/index.js
> +        this.log(foundOfTypeString('sensor', this.senzors.length, 'config.json'))
As this is user input, we should verify that the fields supplied are `'name'` (optional), `'type'` and `'id'` and nothing else.

2016-10-29 19:21 UTC, amlinger commented on src/index.js
> +      } else {
The else clause here seems superfluous, but it's up to you whether you want to keep it or not.

2016-10-29 19:21 UTC, amlinger commented on src/index.js
> +      } else {
The ideal case to me would be if we could print the path where `config.json` was read as well, but that might be a bit over the top for an initial implementation.

2016-10-29 19:21 UTC, amlinger commented on src/lib/telldus-accessory.js
> +      if (s == undefined) {
I'd like to go with `===` as standard.

2016-10-29 19:21 UTC, amlinger commented on src/lib/telldus-accessory.js
> +      if (s == undefined) {
I'd like to go with `===` as standard.

2016-10-29 19:21 UTC, amlinger commented on src/lib/telldus-accessory.js
> +      if (s == undefined) {
I'd like to go with `===` as standard.

2016-10-29 19:27 UTC, jannylund commented on src/index.js
> +      } else {
The `else` clause is simply there for backwards compatibility, but I agree, it could be removed if you are ok with dropping autoconfigured sensors?

2016-10-29 19:29 UTC, jannylund commented on src/index.js
> +        this.log(foundOfTypeString('sensor', this.senzors.length, 'config.json'))
As of the other PR, it's also possible to provide `maxAge`.

2016-10-29 19:31 UTC, jannylund commented on src/lib/telldus-accessory.js
> +      if (s == undefined) {
Fixed.

2016-10-29 19:31 UTC, jannylund commented on src/lib/telldus-accessory.js
> +      if (s == undefined) {
Fixed.

2016-10-29 19:31 UTC, jannylund commented on src/lib/telldus-accessory.js
> +      if (s == undefined) {
Fixed.

2016-10-29 19:35 UTC, amlinger commented on src/index.js
> +      } else {
Sorry for the confusion, that's not what I meant. I just meant that 
```js
if (this.senzors.length > {
    // ...
}
return ...
```
provides the same functionality as 
```js
if (this.senzors.length > {
    // ...
} else {
    return ...
}
```

2016-10-29 19:36 UTC, jannylund commented on src/index.js
> +    this.senzors = config["sensors"] || [];
`devices` are coming from the output of tdtool, since they are configured in `telldus.conf`. The only reason to use `senzors` instead of `sensors` is to avoid confusion with the local variable `sensors` used in the `else` clause.

2016-10-29 19:38 UTC, jannylund commented on src/index.js
> +      } else {
Ok, now I understand. Yeah, that could be done, but in this case I think it's more readable to keep the `else`.

2016-10-29 19:47 UTC, amlinger commented on src/index.js
> +        this.log(foundOfTypeString('sensor', this.senzors.length, 'config.json'))
I saw that, and if you do not wish to address all these constraints in this PR it's fine, we just need to track it in another issue.

2016-10-29 19:50 UTC, amlinger commented on src/index.js
> +    this.senzors = config["sensors"] || [];
I'd really like to avoid this, as sensors can be derived from the config object. Let's keep state to a minimum and rely on the config object instead.

2016-10-29 19:55 UTC, jannylund commented on src/index.js
> +    this.senzors = config["sensors"] || [];
Fixed.

2016-10-29 19:59 UTC, jannylund commented on src/index.js
> +        this.log(foundOfTypeString('sensor', this.senzors.length, 'config.json'))
Let's make it another PR as it otherwise needs changes in the other PR as well.

2016-10-29 20:04 UTC, jannylund commented
I think this one is done now. Please merge it if you agree, and I'll rebase https://github.com/amlinger/homebridge-telldus-tdtool/pull/30

2016-10-29 20:17 UTC, amlinger commented
Thanks for submitting this, looks like a good implementation and a good interface to me. Tracking the progress on feedback to config fields on #35.

2016-10-29 20:18 UTC, merged