Homekit for iOS 10 doesn't maintain the state of the dimmer switch an…
amlinger/homebridge-telldus-tdtool pull request #41
Opened 2016-11-14 16:56 UTC by andlier

…d sometimes dimlevel is not called, or setState and dimlevel are called in random order. This fix will maintain the state of the dimmer and set correct dimlevel even if only setState is called.

2016-11-14 21:44 UTC, amlinger requested changes
Thanks for taking the time, and for rebasing as well! :)

There is still a couple of things we need to attend before this will work as intended. Please have a look at the comments.

2016-11-14 21:44 UTC, amlinger commented on src/lib/telldus-accessory.js
> +        return callback(null, this.dimlevel)
This line can be removed, with the same functionality kept.

2016-11-14 21:44 UTC, amlinger commented on src/lib/telldus-accessory.js
> +      TDtool.dim(percentageToBits(this.dimlevel), this.id).then(out => {
I believe a return statement is needed here, or line `213` will always be executed.

2016-11-14 21:44 UTC, amlinger commented on src/lib/telldus-accessory.js
> +    this.setState(this.dimlevel > 0 ? true : false, callback, context)
This can be substituted for
```js
this.setState(this.dimlevel > 0, callback, context)
```
which is a bit easier to read imo.

2016-12-25 10:51 UTC, amlinger commented
Hi @andlier,

Thank you very much for your contributions this far!

Would you mind addressing the comment regarding the `return`-statement, so that I can merge this?

2016-12-27 15:47 UTC, andlier commented on src/lib/telldus-accessory.js
> +      TDtool.dim(percentageToBits(this.dimlevel), this.id).then(out => {
I've added an else-clause instead to only run the last line when the light is supposed to be turned off.

2016-12-27 15:50 UTC, andlier commented
Between work and family I didn't have time to address these comments until now. I didn't fully understand the return-statement comment, but I hope the else-clause fixes it. Also addressed the other comments to the best of my ability. The code has been working here with several dimmers for the last couple of months without issues.

2016-12-28 12:41 UTC, amlinger commented on src/lib/telldus-accessory.js
> +      TDtool.dim(percentageToBits(this.dimlevel), this.id).then(out => {
That should make it work, thanks!

2016-12-28 12:42 UTC, amlinger approved these changes
Thanks a lot for your update @andlier, I really appreciate it! I'll go ahead and merge this now!

2016-12-28 12:43 UTC, merged